### POST request to add patient

POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Batman",
  "email": "batman@gmail.com",
  "address": "Gotham city(Budruk)",
  "dateOfBirth": "1995-06-05",
  "registeredDate": "2025-03-01"
}

###